name: greenapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  hooks_riverpod: ^2.5.1
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  auto_route: ^8.1.3
  shared_preferences: ^2.2.3
  injectable: ^2.4.0
  get_it: ^7.7.0
  freezed_annotation: ^2.4.1
  flutter_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5

  firebase_auth: ^5.1.0
  firebase_storage: ^12.0.1
  cloud_firestore: ^5.0.1

  flutter_native_splash: ^2.4.0
  flutter_gemini: ^2.0.4
  flutter_dotenv: ^5.1.0
  image_picker: ^1.1.2
  animated_bottom_navigation_bar: ^1.3.3
  camera: ^0.11.0+1   
  mobile_scanner: ^5.1.1
  qr_scanner_overlay: ^0.0.2
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  country_code_picker: ^3.0.0
  geolocator: ^12.0.0




  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  injectable_generator: ^2.6.1
  freezed: ^2.5.2


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - .env
     - assets/images/   
  
  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
